#!/usr/bin/env python3
"""Validate and synchronize the skill catalog without third-party patches."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import uuid


DEFAULT_ROOT = Path(__file__).resolve().parents[4]


def load_json(path: Path):
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def atomic_json(path: Path, value) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    temporary.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def tree_digest(directory: Path, exclude: tuple[str, ...] = (), overrides: dict | None = None) -> str:
    digest = hashlib.sha256()
    for path in sorted(item for item in directory.rglob("*") if item.is_file()):
        if path.relative_to(directory).as_posix() in exclude:
            continue
        relative = path.relative_to(directory).as_posix().encode()
        digest.update(relative)
        digest.update(b"\0")
        digest.update((overrides or {}).get(path.relative_to(directory).as_posix(), path.read_bytes()))
        digest.update(b"\0")
    return digest.hexdigest()


def codex_overlay(item: dict) -> str:
    """Add host metadata without rewriting any upstream file."""
    metadata = item["codex"]
    return (
        "interface:\n"
        f"  display_name: {json.dumps(metadata['displayName'], ensure_ascii=False)}\n"
        f"  short_description: {json.dumps(metadata['shortDescription'], ensure_ascii=False)}\n"
        f"  default_prompt: {json.dumps('Use $vendor-mattpocock:' + item['name'] + ' for this task.')}\n"
        "policy:\n"
        f"  allow_implicit_invocation: {'false' if item['invocation'] == 'user' else 'true'}\n"
    )


def skill_relative_path(catalog: 'Catalog', item: dict) -> Path:
    base = Path('plugins') / item['plugin'] / 'skills'
    relative = Path(item['path']).relative_to(base)
    if '..' in relative.parts or relative.name != item['name']:
        raise ValueError(f"invalid skill path: {item['path']}")
    return relative


def frontmatter_name(skill_dir: Path) -> str | None:
    skill_file = skill_dir / "SKILL.md"
    if not skill_file.is_file():
        return None
    match = re.search(r"(?m)^name:\s*[\"']?([^\"'\n]+)[\"']?\s*$", skill_file.read_text(encoding="utf-8"))
    return match.group(1).strip() if match else None


def run(command: list[str], cwd: Path | None = None) -> str:
    completed = subprocess.run(command, cwd=cwd, text=True, capture_output=True)
    if completed.returncode:
        detail = completed.stderr.strip() or completed.stdout.strip()
        raise RuntimeError(f"command failed: {' '.join(command)}\n{detail}")
    return completed.stdout.strip()


class Catalog:
    def __init__(self, root: Path):
        self.root = root.resolve()
        self.skills_path = self.root / "registry/skills.json"
        self.workflows_path = self.root / "registry/workflows.json"
        self.skills_doc = load_json(self.skills_path)
        self.workflows_doc = load_json(self.workflows_path)
        self.skills = {item["name"]: item for item in self.skills_doc["skills"]}

    def source(self, source_id: str):
        try:
            return self.skills_doc["sources"][source_id]
        except KeyError as error:
            raise ValueError(f"unknown source: {source_id}") from error

    def selected(self, source_id: str):
        return [
            item for item in self.skills_doc["skills"]
            if item.get("origin", {}).get("source") == source_id
        ]

    def save_skills(self) -> None:
        atomic_json(self.skills_path, self.skills_doc)


def render_catalog(catalog: Catalog) -> str:
    source_locks = {}
    for source_id, source in catalog.skills_doc.get("sources", {}).items():
        lock_path = catalog.root / source["lockPath"]
        source_locks[source_id] = load_json(lock_path) if lock_path.is_file() else None

    lines = [
        "# Maintained workflow catalog",
        "",
        "> Generated from `registry/skills.json` and `registry/workflows.json`.",
        "> Do not edit this file directly.",
        "",
        "## Workflows",
        "",
    ]
    for workflow in catalog.workflows_doc["workflows"]:
        chain = " → ".join(f"`{name}`" for name in workflow["skills"])
        lines.extend([
            f"### {workflow['title']}",
            "",
            f"- ID: `{workflow['id']}`",
            f"- Entry: `${workflow['entry']}`",
            f"- Chain: {chain}",
            f"- Outcome: {workflow['outcome']}",
            "",
        ])

    lines.extend(["## Matt stage navigation", "", "Stage numbers are navigation, not mandatory execution order. See the Matt plugin's README.md and PROJECT-SETUP.md for routes and project prerequisites.", ""])
    for stage in catalog.skills_doc.get('stages', []):
        members = [item for item in catalog.skills_doc['skills'] if item.get('stage') == stage['id']]
        lines.append(f"- **{stage['id']} — {stage['title']}**: " + ', '.join(f"`{item['name']}`" for item in members))
    lines.extend(["", "## Skills", "", "| Skill | Invocation | Ownership | Source |", "|---|---|---|---|"])
    for item in sorted(catalog.skills_doc["skills"], key=lambda value: value["name"]):
        origin = item.get("origin")
        if origin:
            lock = source_locks.get(origin["source"])
            commit = lock["commit"][:7] if lock else "unlocked"
            source_text = f"{origin['source']}@{commit}"
        else:
            source_text = "this repository"
        lines.append(
            f"| `{item['name']}` | {item['invocation']} | {item['ownership']} | {source_text} |"
        )

    exclusions = []
    for source_id, source in catalog.skills_doc.get("sources", {}).items():
        for item in source.get("exclusions", []):
            exclusions.append((source_id, item))
    if exclusions:
        lines.extend(["", "## Deliberate upstream exclusions", ""])
        for source_id, item in sorted(exclusions, key=lambda value: value[1]["name"]):
            lines.append(f"- `{item['name']}` ({source_id}): {item['reason']}")

    referenced = {
        name for workflow in catalog.workflows_doc["workflows"] for name in workflow["skills"]
    }
    unreferenced = sorted(set(catalog.skills) - referenced)
    lines.extend(["", "## Static audit", ""])
    if unreferenced:
        lines.append("- Unreferenced skills: " + ", ".join(f"`{name}`" for name in unreferenced))
    else:
        lines.append("- Every registered skill appears in at least one maintained workflow.")
    lines.extend([
        "- Unreferenced does not mean unused; real usage requires user evidence or telemetry.",
        "- Responsibility overlap still requires semantic review by the user.",
        "",
    ])
    return "\n".join(lines)


def render_stage_guide(catalog: Catalog) -> str:
    lines = ['# Matt Pocock Skills：按工作阶段选择', '',
             '> 从 registry/skills.json 生成。编号表示常用阶段，不是必须依次执行的步骤。', '',
             '每个 skill 仅保存一份；学习、领域建模、测试、交接可以在任何阶段按需进入。', '',
             '先看 [常用路线](WORKFLOWS.md)，需要 tracker 的项目先看 [项目接入](PROJECT-SETUP.md)。', '',
             '上游 SKILL.md、配套文档、脚本与资源保持原样。仅 agents/openai.yaml 作 Codex 适配；原始 YAML 保存在 UPSTREAM.lock.json，原始树与打包树分别校验。', '']
    for stage in catalog.skills_doc.get('stages', []):
        lines += [f"## {stage['id']} · {stage['title']}", '', '| Skill | 任务类型 | 调用方式 |', '|---|---|---|']
        for item in catalog.selected('mattpocock'):
            if item.get('stage') != stage['id']: continue
            path = skill_relative_path(catalog, item).as_posix()
            mode = '显式调用' if item['invocation'] == 'user' else '自动匹配或显式调用'
            lines.append(f"| [{item['name']}](skills/{path}/SKILL.md) | {item['codex']['shortDescription']} | {mode} |")
        lines.append('')
    lines += ['## 技能依赖与项目先决条件', '', '这些是运行时调用依赖，不代表用户需要提前手动执行。分支使用的技能列入依赖，以便安装和移除检查保证流程完整。', '', '| Skill | 调用依赖 | 项目前提 |', '|---|---|---|']
    for item in catalog.selected('mattpocock'):
        if item.get('requires') or item.get('prerequisites'):
            lines.append(f"| `{item['name']}` | {', '.join('`'+n+'`' for n in item.get('requires', [])) or '—'} | {'; '.join(item.get('prerequisites', [])) or '—'} |")
    lines += ['', '依赖 setup-matt-pocock-skills 的配置要求由项目接入文档说明；该 setup skill 未安装。YAML 不能替代项目配置，也不改变上游发布、提交或教学产物行为。', '']
    return '\n'.join(lines)


def write_catalog(catalog: Catalog, apply: bool) -> int:
    output = render_catalog(catalog)
    target = catalog.root / "plugins/workflow-hub/skills/workflow-guide/references/catalog.md"
    if not apply:
        print(output)
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(output, encoding="utf-8")
    if catalog.skills_doc.get('stages'):
        (catalog.root / 'plugins/vendor-mattpocock/README.md').write_text(render_stage_guide(catalog), encoding='utf-8')
    manifest_path = catalog.root / "plugins/workflow-hub/.codex-plugin/plugin.json"
    manifest = load_json(manifest_path)
    base_version = manifest["version"].split("+")[0]
    catalog_digest = hashlib.sha256(output.encode()).hexdigest()[:12]
    manifest["version"] = f"{base_version}+catalog.{catalog_digest}"
    atomic_json(manifest_path, manifest)
    print(f"updated {target.relative_to(catalog.root)}")
    return 0


def validate(catalog: Catalog) -> int:
    errors: list[str] = []
    entries = catalog.skills_doc.get("skills", [])
    names = [item.get("name") for item in entries]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        errors.append("duplicate registry names: " + ", ".join(duplicates))
    stages = {stage['id'] for stage in catalog.skills_doc.get('stages', [])}

    for item in entries:
        name = item.get("name")
        if item.get('codex') and item.get('stage') not in stages:
            errors.append(f"{name}: unknown stage")
        if item.get('codex') and skill_relative_path(catalog, item).parts != (item['stage'], name):
            errors.append(f"{name}: destination does not match stage")
        path = catalog.root / item.get("path", "")
        if not path.is_dir():
            errors.append(f"{name}: missing directory {item.get('path')}")
            continue
        actual_name = frontmatter_name(path)
        if actual_name != name:
            errors.append(f"{name}: SKILL.md declares {actual_name!r}")
        for dependency in item.get("requires", []):
            if dependency not in catalog.skills:
                errors.append(f"{name}: missing dependency {dependency}")
        if item.get("ownership") == "vendored" and not item.get("origin"):
            errors.append(f"{name}: vendored entry has no origin")

    for workflow in catalog.workflows_doc.get("workflows", []):
        if workflow.get("entry") not in workflow.get("skills", []):
            errors.append(f"workflow {workflow.get('id')}: entry is not in skills")
        for name in workflow.get("skills", []):
            if name not in catalog.skills:
                errors.append(f"workflow {workflow.get('id')}: unknown skill {name}")

    discovered = set()
    for pattern in ("plugins/*/skills/**/SKILL.md", ".agents/skills/*/SKILL.md"):
        for skill_file in catalog.root.glob(pattern):
            discovered.add(skill_file.parent.relative_to(catalog.root).as_posix())
    registered_paths = {item["path"] for item in entries}
    for path in sorted(discovered - registered_paths):
        errors.append(f"unregistered skill directory: {path}")
    for path in sorted(registered_paths - discovered):
        errors.append(f"registered path is not discoverable: {path}")

    for source_id, source in catalog.skills_doc.get("sources", {}).items():
        excluded_names = [item.get("name") for item in source.get("exclusions", [])]
        duplicate_exclusions = sorted({name for name in excluded_names if excluded_names.count(name) > 1})
        if duplicate_exclusions:
            errors.append(f"{source_id}: duplicate exclusions: {', '.join(duplicate_exclusions)}")
        selected_names = {item["name"] for item in catalog.selected(source_id)}
        overlap = sorted(selected_names.intersection(excluded_names))
        if overlap:
            errors.append(f"{source_id}: selected and excluded: {', '.join(overlap)}")
        lock_path = catalog.root / source["lockPath"]
        if not lock_path.is_file():
            errors.append(f"{source_id}: missing lock {source['lockPath']}")
            continue
        lock = load_json(lock_path)
        locked = {item["name"]: item for item in lock.get("skills", [])}
        selected = catalog.selected(source_id)
        if set(locked) != {item["name"] for item in selected}:
            errors.append(f"{source_id}: lock selection differs from registry")
        for item in selected:
            local_path = catalog.root / item["path"]
            lock_item = locked.get(item["name"])
            if local_path.is_dir() and lock_item:
                original_yaml = lock_item.get('upstreamOpenaiYaml')
                overlays = ('agents/openai.yaml',) if item.get('codex') and original_yaml is None else ()
                overrides = {'agents/openai.yaml': original_yaml.encode('utf-8')} if original_yaml is not None else {}
                digest = tree_digest(local_path, overlays, overrides)
                if digest != lock_item.get("treeSha256"):
                    errors.append(f"{item['name']}: vendored content differs from lock")
                if item.get('codex'):
                    overlay = local_path / 'agents/openai.yaml'
                    if not overlay.is_file() or overlay.read_text() != codex_overlay(item):
                        errors.append(f"{item['name']}: Codex overlay differs from registry")
                    if tree_digest(local_path) != lock_item.get('packagedTreeSha256'):
                        errors.append(f"{item['name']}: packaged content differs from lock")
                    if lock_item.get('path') != item['path']:
                        errors.append(f"{item['name']}: packaged path differs from lock")
                skill_relative_path(catalog, item)
        plugin_root = catalog.root / "plugins" / source["plugin"]
        if not (plugin_root / source["licensePath"]).is_file():
            errors.append(f"{source_id}: preserved license is missing")
        if not (plugin_root / "THIRD_PARTY_NOTICES.md").is_file():
            errors.append(f"{source_id}: third-party notice is missing")

    for plugin_dir in sorted((catalog.root / "plugins").iterdir()):
        manifest = plugin_dir / ".codex-plugin/plugin.json"
        if not manifest.is_file():
            errors.append(f"{plugin_dir.name}: missing plugin manifest")
            continue
        plugin = load_json(manifest)
        if plugin.get("name") != plugin_dir.name:
            errors.append(f"{plugin_dir.name}: manifest name mismatch")

    catalog_path = catalog.root / "plugins/workflow-hub/skills/workflow-guide/references/catalog.md"
    stage_path = catalog.root / 'plugins/vendor-mattpocock/README.md'
    if stages and (not stage_path.is_file() or stage_path.read_text(encoding='utf-8') != render_stage_guide(catalog)):
        errors.append('generated Matt stage guide is stale; run render-catalog --apply')
    if not catalog_path.is_file() or catalog_path.read_text(encoding="utf-8") != render_catalog(catalog):
        errors.append("generated workflow catalog is stale; run render-catalog --apply")

    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    print(f"OK: {len(entries)} skills and {len(catalog.workflows_doc['workflows'])} workflows validated")
    return 0


def inventory(catalog: Catalog, as_json: bool) -> int:
    if as_json:
        print(json.dumps(catalog.skills_doc["skills"], indent=2, ensure_ascii=False))
        return 0
    print(f"{'SKILL':32} {'OWNER':9} {'CALL':6} LOCATION")
    for item in sorted(catalog.skills_doc["skills"], key=lambda value: value["name"]):
        print(f"{item['name']:32} {item['ownership']:9} {item['invocation']:6} {item['path']}")
    return 0


def remote_head(source: dict) -> str:
    output = run(["git", "ls-remote", source["repository"], f"refs/heads/{source['branch']}"])
    if not output:
        raise RuntimeError(f"branch not found: {source['branch']}")
    return output.split()[0]


def check_upstream(catalog: Catalog, source_id: str) -> int:
    source = catalog.source(source_id)
    head = remote_head(source)
    lock_path = catalog.root / source["lockPath"]
    locked = load_json(lock_path).get("commit") if lock_path.is_file() else None
    print(f"source:  {source_id}")
    print(f"locked:  {locked or 'none'}")
    print(f"upstream:{head}")
    print("status:  " + ("current" if locked == head else "update available"))
    return 0


def checkout_source(source: dict, ref: str, destination: Path) -> tuple[str, str]:
    run(["git", "clone", "--quiet", source["repository"], str(destination)])
    run(["git", "checkout", "--quiet", ref], cwd=destination)
    commit = run(["git", "rev-parse", "HEAD"], cwd=destination)
    committed_at = run(["git", "show", "-s", "--format=%cI", "HEAD"], cwd=destination)
    return commit, committed_at


def sync_vendor(catalog: Catalog, source_id: str, ref: str | None, apply: bool) -> int:
    source = catalog.source(source_id)
    selected = catalog.selected(source_id)
    if not selected:
        raise ValueError(f"no skills selected for source: {source_id}")
    requested_ref = ref or remote_head(source)
    with tempfile.TemporaryDirectory(prefix=f"skill-sync-{source_id}-") as temporary:
        checkout = Path(temporary) / "upstream"
        commit, committed_at = checkout_source(source, requested_ref, checkout)
        stage = Path(temporary) / "skills"
        stage.mkdir()
        lock_skills = []
        changed = []
        for item in sorted(selected, key=lambda value: value["name"]):
            source_path = checkout / item["origin"]["path"]
            if not source_path.is_dir():
                raise RuntimeError(f"upstream path missing: {item['origin']['path']}")
            if frontmatter_name(source_path) != item["name"]:
                raise RuntimeError(f"upstream name mismatch for {item['name']}")
            destination = stage / skill_relative_path(catalog, item)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(source_path, destination)
            digest = tree_digest(destination)
            original_yaml = None
            if item.get('codex'):
                overlay = destination / 'agents/openai.yaml'
                if overlay.exists():
                    original_yaml = overlay.read_text(encoding='utf-8')
                overlay.parent.mkdir(exist_ok=True)
                overlay.write_text(codex_overlay(item), encoding='utf-8')
            packaged_digest = tree_digest(destination)
            local = catalog.root / item["path"]
            if not local.is_dir() or tree_digest(local) != packaged_digest:
                changed.append(item["name"])
            lock_skills.append({
                "name": item["name"],
                "sourcePath": item["origin"]["path"],
                "treeSha256": digest,
                "packagedTreeSha256": packaged_digest,
                "path": item['path'],
                "upstreamOpenaiYaml": original_yaml,
            })

        license_source = checkout / source["licensePath"]
        if not license_source.is_file():
            raise RuntimeError(f"upstream license missing: {source['licensePath']}")
        print(f"source:  {source_id}")
        print(f"commit:  {commit}")
        print("changed: " + (", ".join(changed) if changed else "none"))
        if not apply:
            print("dry run; pass --apply to replace the selected vendored tree")
            return 0

        plugin_root = catalog.root / "plugins" / source["plugin"]
        target = plugin_root / "skills"
        staging = plugin_root / f".skills-staging-{uuid.uuid4().hex}"
        backup = plugin_root / f".skills-backup-{uuid.uuid4().hex}"
        shutil.copytree(stage, staging)
        try:
            if target.exists():
                os.replace(target, backup)
            os.replace(staging, target)
        except Exception:
            if target.exists():
                shutil.rmtree(target)
            if backup.exists():
                os.replace(backup, target)
            raise
        else:
            if backup.exists():
                shutil.rmtree(backup)

        shutil.copy2(license_source, plugin_root / source["licensePath"])
        lock = {
            "schemaVersion": 1,
            "source": source_id,
            "repository": source["repository"],
            "branch": source["branch"],
            "commit": commit,
            "committedAt": committed_at,
            "license": source["license"],
            "licensePath": source["licensePath"],
            "skills": lock_skills,
        }
        atomic_json(catalog.root / source["lockPath"], lock)

        manifest_path = plugin_root / ".codex-plugin/plugin.json"
        manifest = load_json(manifest_path)
        base_version = manifest["version"].split("+")[0]
        selection_payload = json.dumps(lock_skills, sort_keys=True, separators=(",", ":")).encode()
        selection_digest = hashlib.sha256(selection_payload).hexdigest()[:12]
        manifest["version"] = f"{base_version}+upstream.{commit[:7]}.selection.{selection_digest}"
        atomic_json(manifest_path, manifest)
        write_catalog(catalog, True)
        print("sync applied")
        return 0


def remove_skill(catalog: Catalog, name: str, apply: bool) -> int:
    item = catalog.skills.get(name)
    if not item:
        raise ValueError(f"unknown skill: {name}")
    if item.get("ownership") != "vendored":
        raise ValueError("remove only automates vendored skills; review original skills manually")
    dependency_blockers = sorted(
        other["name"] for other in catalog.skills_doc["skills"] if name in other.get("requires", [])
    )
    workflow_blockers = sorted(
        workflow["id"] for workflow in catalog.workflows_doc["workflows"] if name in workflow["skills"]
    )
    if dependency_blockers or workflow_blockers:
        if dependency_blockers:
            print("blocked by skill dependencies: " + ", ".join(dependency_blockers))
        if workflow_blockers:
            print("blocked by workflows: " + ", ".join(workflow_blockers))
        return 1
    print(f"ready to remove complete directory: {item['path']}")
    if not apply:
        print("dry run; pass --apply after the exact removal is approved")
        return 0

    target = (catalog.root / item["path"]).resolve()
    expected_parent = (catalog.root / "plugins" / item["plugin"] / "skills").resolve()
    if not target.is_relative_to(expected_parent) or target == expected_parent or target.name != name:
        raise RuntimeError("refusing removal outside the owning plugin skills directory")
    shutil.rmtree(target)
    catalog.skills_doc["skills"] = [entry for entry in catalog.skills_doc["skills"] if entry["name"] != name]
    catalog.save_skills()
    source = catalog.source(item["origin"]["source"])
    lock_path = catalog.root / source["lockPath"]
    lock = load_json(lock_path)
    lock["skills"] = [entry for entry in lock["skills"] if entry["name"] != name]
    atomic_json(lock_path, lock)
    write_catalog(catalog, True)
    print("removed; tracked content remains recoverable from Git")
    return 0


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(description=__doc__)
    root.add_argument("--repo", type=Path, default=DEFAULT_ROOT)
    commands = root.add_subparsers(dest="command", required=True)
    inventory_parser = commands.add_parser("inventory")
    inventory_parser.add_argument("--json", action="store_true")
    commands.add_parser("validate")
    render_parser = commands.add_parser("render-catalog")
    render_parser.add_argument("--apply", action="store_true")
    check_parser = commands.add_parser("check-upstream")
    check_parser.add_argument("--source", required=True)
    sync_parser = commands.add_parser("sync-vendor")
    sync_parser.add_argument("--source", required=True)
    sync_parser.add_argument("--ref")
    sync_parser.add_argument("--apply", action="store_true")
    remove_parser = commands.add_parser("remove")
    remove_parser.add_argument("--skill", required=True)
    remove_parser.add_argument("--apply", action="store_true")
    return root


def main() -> int:
    args = parser().parse_args()
    try:
        catalog = Catalog(args.repo)
        if args.command == "inventory":
            return inventory(catalog, args.json)
        if args.command == "validate":
            return validate(catalog)
        if args.command == "render-catalog":
            return write_catalog(catalog, args.apply)
        if args.command == "check-upstream":
            return check_upstream(catalog, args.source)
        if args.command == "sync-vendor":
            return sync_vendor(catalog, args.source, args.ref, args.apply)
        if args.command == "remove":
            return remove_skill(catalog, args.skill, args.apply)
    except (OSError, ValueError, RuntimeError, json.JSONDecodeError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
